server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lostandfound

mybatis:
  type-aliases-package: team.system.lostandfoundserver.mapper #mybatis扫描包
  configuration:
    map-underscore-to-camel-case: true #开启mybatis命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启mybatis打印sql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启mybatis-plus打印sql